#!/bin/sh
gnuplot << EOF
unset label
set terminal pngcairo size 800,600 enhanced
set output "$(echo $1 | sed s/\.dat//g).png"
set autoscale
plot "$1" using 1:2 with lines title "Function", \
     '' using 1:3 with lines title "Expected"
EOF
