#+TITLE:     Project #4 Brood Selection
#+AUTHOR:    Andrew Schwartzmeyer
#+EMAIL:     schw2620@vandals.uidaho.edu
#+DATE:      2014-05-09 Fri
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LATEX_HEADER: \usepackage{lmodern}

#+BEGIN_ABSTRACT
For the University of Idaho's Evolutionary Computation (CS 472)
Project #4 I studied the cost of brood selection for increasing
performance on the Santa Fe Trail problem.

The code can be found at:
=https://github.com/andschwa/uidaho-cs472-project4=
#+END_ABSTRACT

* Build :noexport:
Makes use of autotools. Necessary files:
- configure.ac (with help from autoscan)
- Makefile.am
- m4/* for macros

To configure and build:
#+begin_src sh
autoreconf -vfi && ./configure && make
#+end_src

Boost must be built using the same compiler, so for OS X,
=./tools/build/v2/user-config.jam= needs the directive =using darwin :
4.8 : g++-4.8 ;=. This will force the darwin toolset to use =g++-4.8=
(install via homebrew). See

Boost should then be bootstrapped like thus:

#+begin_src sh
./bootstrap.sh --with-libraries=program_options --with-toolset=darwin
#+end_src

And then built with =./b2= and installed with =./b2 install=.

* Assignment :noexport:
** DONE Project #2a Genetic Program
   DEADLINE: <2014-03-07 Fri>
[[http://www2.cs.uidaho.edu/~cs472_572/s14/GPProjectA.html][From Professor Terry Soule]]
This is the first subproject of the GP project. The goal of this
subproject is to create a population of GP tree structures for a
symbolic regression problem.  If you want to use it, or refer to it, I
have written a node and an individual class that uses pointers to
build and evaluate random expression trees. Trees are build of nodes,
which point to each other.

node.h
node.cpp
individual.h
individual.cpp
test.cpp

To compile the test main program use:

=g++ test.cpp node.cpp individual.cpp=

For this subproject you only need the following functionallity:

- Generate full random expression individuals.
- The expression trees should have, at least, the non-teminals: +,
  -, *, /.
- The expression trees should have, at least, the teminals: X (the
  input variable) and constants.
- The ability to copy individuals.
- The ability to evaluate individuals.
- The ability to erase individuals.
- The ability to calculate the size (number of terminals and
  non-terminals) of individuals.
- The ability to create a population of individuals and to find the
  best and average fitness of the population, and the average size of
  the individuals in the population.
- Individuals should represent expression trees, but may be coded as a
  different type of data structure (e.g. a tree stored in an
  array). For now you may choose your own fitness function, i.e. your
  own set of x,y points that the GP should evolved an expression to
  fit.

For the report:

- Project Write-up: Write a short paper describing the results of your
  project that includes the following sections:
- Algorithm descriptions - Description of the GP so far. Be careful to
  include all of the details someone would need to replicate your
  work.
- Individual description - Description of the structure of your
  individuals. Be careful to include all of the details someone would
  need to replicate your work.
- Results - Basically, does it seem to be working.
- Conclusions - If it's not working, why not. And what are then next
  steps to complete the project.

** DONE Project #2b Genetic Program
   DEADLINE: <2014-03-14 Fri>
This is the second subproject of the GP project. The goal of this subproject is to finish the pieces of the GP for a symbolic regression problem.
For this subproject you will need to complete the GP including the following functionallity (in addition to the functions from the previous assignment):

- [X] Add a conditional to the function set of the expression trees.
- [X] Mutation
- [X] Crossover of two trees
- [X] Selection
- [X] Elitism if you are using a generational model
- [X] Test the GP to make sure that it is working.

Project Write-up: For this subproject you only need a description of
the general algorithm:

- [X] generational or steady-state
- [X] how mutation works
- [X] the selction mechanism, etc.
- [X] a description of any problems so far

Note that the write-up may be fairly short.
** DONE Project #2 Genetic Program
   DEADLINE: <2014-03-23 Sun>

This is the final part of Project 2. For this project you need to
present a summary of your GP program and the results. Here is a
template for the summary in Word and pdf (and the latex). Note that
for this project you do not need to do a lot of writting. An abstract,
fill in the table summarizing your algorithms, two graphs, and a
conclusion/discussion.

Given function:
[
if (x < -9)
y = 0.4 * ((20 + x)^{2} + 7 * x)
else if (x < 10)
y = 0.5 * x
else
 y = x + 5 * sin(0.5 * x)
] + random(5, -5)

** DONE Project #3 Project #3 Santa Fe Trail
   DEADLINE: <2014-04-14 Mon>

For this project you need to create a genetic program for the Santa Fe
Trail problem. You will probably want to work from (a copy of) the
code for Project 2. If so you will need to make the following changes:

- [X] Change the non-terminal/operator set to at least: prog2, prog3,
  and iffoodahead
- [X] Change the terminal/leaf set to at least: left, forward,
  right. (You may add additional non-termials or terminals if you
  want.)
- [X] Change the evaluate function at both the individual and node levels.

For the write-up you may use the same template as for Project 2, but
instead of a figure showing the best evolved function (Figure 2 in the
template) include at least one figure showing the path taken by the
best evolved ant. This does not have to be fancy graphics, an ASCII
figure will do.

** TODO Project #4
   DEADLINE: <2014-05-09 Fri>
The goal of this project is to perform an experiment to test a
hypothesis relating to evolutionary computation or to write an
evolutionary algorithm for a specific (challenging) application. The
exact hypothesis or application is up to you (but see subproject
4a). If you plan to test a hypothesis make sure that it is clear, well
defined, and reasonable to answer experimentally. Ideally you can
claim "if my hypothesis is correct and if I perform this experiment
then the result will be X and if the result is not X then my
hypothesis is incorrect".

The simpler and more specific your hypothesis is, the easier it will
be to do this project, and you should understand the reasoning behind
your hypothesis. For example, if your hypothesis is "using random
trails in the artificial ant/Sante Fe trail problem will improve
results" you're going to have a hard time - what does improve mean?
Why should they improve?

On the other hand if your hypothesis is "using random trails in the
artificial ant/Santa Fe trail problem will on average produce
individuals whose fitness is higher, although they may take longer to
evolve, because the random trails will force GP to evolve a more
general and hence more successful soluton" it's going to be much
easier to complete the project.

If you plan to tackle a specific application you should have a
specific reason why the application is interesting and challenging.

Project Requirements:

- A clearly defined hypothesis or applcation.
- A clearly defined experiment to test the hypothesis or a clearly
  defined algorithm for the application.
- The code to run the experiment. I strongly encourage you to figure
  out a way to reuse code from previous experiments.

Project Write-up: You must write a short paper describing the results
of your project. The paper should be formatted using the [[http://www.acm.org/sigs/publications/proceedings-templates][ACM SIG
Proceedings Templates]]. This is a standard format for many research
conferences. Note that there is a Word and a Latex template, you may
use either one.  The final paper should include the following
sections:

- Abstract - a short (~200 words) summary of what you did and what the
  results were.
- Introduction - including: the hypothesis or application, what
  evidence you have for and against the hypothesis or previous work on
  the applicaiton, include at least 3 published sources.
- Experiment description - including:
  - The test problem(s) used in the experiments.
  - A description of the evolutionary algorithm used in the experiments.
  - How fitness was measured.
  - What parameters were used.
  - If you are testing a hypothesis you should include a clear
    explanation of how the results would support, or refute, the
    hypothesis. You should be able to say, before running any
    experiments, 'if I get these results it means the hypothesis is
    confirmed (or at least supported) and if I get these results the
    hypothesis is refuted'.
- Results:
  - There should be at least 5-10 trials per experiment.
  - Include graphs and/or tables to make it easy to understand the results.
  - Make sure that the graphs and tables are clearly labeled.
  - Explain how the results support or refute your hypothesis or how
    well you algorithm did on the application problem.
- Conclusions
- References
* Algorithm Information :noexport:
#+ATTR_LATEX: :align |l|p{4in}|
|------------------+-----------------------------------------------------------|
| Algorithm type   | Generational                                              |
|------------------+-----------------------------------------------------------|
| Population size  | 1024                                                      |
|------------------+-----------------------------------------------------------|
| Selection method | Tournament of size 3                                      |
|------------------+-----------------------------------------------------------|
| Elitism          | Replace random 2 offspring with previous best             |
|------------------+-----------------------------------------------------------|
| Crossover method | Subtree with 90 percent chance to choose an internal node |
|------------------+-----------------------------------------------------------|
| Crossover rate   | 80 percent                                                |
|------------------+-----------------------------------------------------------|
| Mutation method  | 2 percent chance per node to mutate                       |
|------------------+-----------------------------------------------------------|
| Operation set    | prog-2, prog-3, if-food-ahead                             |
|------------------+-----------------------------------------------------------|
| Terminal set     | left, right, forward                                      |
|------------------+-----------------------------------------------------------|
| Fitness function | Number of food pieces eaten                               |
|------------------+-----------------------------------------------------------|
| Size control     | Size penalty of 0.1 * total applied to fitness            |
|------------------+-----------------------------------------------------------|

** Details

Not much has changed since Project #2.  The genetic program was
revamped to imitate "ants" crawling along the Santa Fe Trail, with the
goal of finding and eating food.  The genetic algorithm, population
size, selection method, elitism, crossover method, and crossover rate
are the same as previous.

To do this, a map class was implemented which handled the details of
having a 32 by 32 toroidial grid of blank, food, and marked locations.
This map had a position struct for the (x, y) coordinate pair and
direction of the ant, along with the width and height of the grid, and
the current tick count, maximum ticks, score, and maximum score (that
is, available food).  Its primary interface was =left()=, =right()=,
=forward()= and =look()= functions; the first three increment the tick
count, where =left()= and =right()= change the ant's direction,
=forward()= moves the ant forward and consumes food (incrementing the
score need be), and =look()= returns a boolean value used by the
=if-food-ahead= function.  The individual's evaluate function receives
a =Map= object by value (a copy of the original), and passes that by
reference to the root node's evaluate function in a =while= loop
conditioned on the ant being =active()= (that is, still has ticks
left).  Inside the evaluation method, when the maximum number of steps
is reached, it returns.  In this way, the ant's "decision" tree can be
continusouly evaluted while updating the map with the corresponding
movements, with =prog-2=, =prog-3=, and =if-food-ahead= working as
expected (causing more than one move per evalution of the tree).

The mutation sequence is run on every new individual in the offspring
generation.  With a two percent chance per node, it mutates a leaf
node into another leaf node, and an internal node into another
internal node.  When an internal node of arity three (=prog-3=) is
mutated into one of arity two (=prog-2= and =if-food-ahead=), the last
child node is popped from its vector to correct the arity.
Conversely, when a node of arity two is mutated into one of arity
three, a new node is created.  This node is made with an equal chance
to be "grown" or "fully" generated.  Its maximum depth is randomly
chosen from between zero and four.  This depth range was chosen with
the consideration that the trees popped in the previous correction may
have been quite large and thus should be compensated for, but I
additionally did not want to introduce unwanted code growth.

The fitness of the ant is the number of food pieces it can eat on the
on the Santa Fe Trail subject to the constraint of 600 ticks, where a
tick is either turning left or right, or moving forward.  As such,
this became a maximization algorithm.  To control code growth, a size
penalty of ten percent of the total tree size is substracted from this
fitness when used in comparisons.  The adjusted fitness (as presented
graphically), is the score (that is, actual number of food pieces
eaten, no penalties applied) divided by the total number of food
pieces available (in our case, 90).
* Requirements
** Hypothesis
Brood selection is computationally effective at improving the results
of a genetic program solving the Santa Fe Trail problem, where
'computationally effective' means that the extra computation cost
incurred by the brood selection process is compensated for by its
improvement to the crossover process. The 'effectiveness' is measured
by the final fitness divided by CPU time after a set number of
generations.

** Experiment details

| Property              | Value | Description                                                                |
|-----------------------+-------+----------------------------------------------------------------------------|
| Algorithm type        |       | Generational                                                               |
| Non-terminal set      |       | prog-2, prog-3, if-food-ahead                                              |
| Terminal set          |       | turn left, turn right, move forward                                        |
| Generations           |   512 | Number of generations per run                                              |
| Population size       |  1024 | Number of individuals per generation                                       |
| Evaluation ticks      |   600 | Number of ticks individual (ant) may use for evaluation                    |
| Grow chance           |   0.5 | Ramped half-and-half initial tree / subtree mutation generation            |
| Minimum depth         |     2 | Minimum initial tree / subtree mutation generation depth                   |
| Maximum depth         |     6 | Maximum initial tree / subtree mutation generation depth                   |
| Depth limit           |    14 | Maximum depth of tree before being selected out                            |
| Tournament size       |     3 | Number of individuals drawn per tournament selection                       |
| Elitism size          |     2 | Number of individuals replaced by best individual per generation           |
| Fitter size           |   320 | Size of fitter population for over-selection                               |
| Over-selection chance |   0.8 | Chance that selection will be done from the fitter population              |
| Crossover chance      |   0.9 | Chance per pair of individuals to undergo crossover / brood selection      |
| Internals chance      |   0.9 | During subtree crossover, chance that selected nodes will be non-terminals |
| Mutate chance         |  0.05 | Chance per individual that it will undergo mutation                        |
| Brood selection       |  2-12 | Variable size of brood, where two is 'no' brood (normal crossover size)    |
