#!/bin/sh
gnuplot << EOF
unset label
# png output
set terminal pngcairo size 800,600 enhanced
set output "$(echo $1 | sed s/\.dat//g).png"
set autoscale
# better lines
set style line 1 lc rgb '#8b1a0e' pt 1 ps 1 lt 1 lw 2 # --- red
set style line 2 lc rgb '#5e9c36' pt 1 ps 1 lt 1 lw 2 # --- green
# better axes
set style line 11 lc rgb '#808080' lt 1
set border 3 back ls 11
set tics nomirror
# add grid
set style line 12 lc rgb '#808080' lt 0 lw 1
set grid back ls 12
# plot function
plot "$1" using 1:2 with lines title "Function", \
     '' using 1:3 with lines title "Expected"
EOF
